<?php
echo '';
echo '<html>';
echo '<div class="moon"></div>';
echo '<div class="moon__crater moon__crater1"></div>';
echo '<div class="moon__crater moon__crater2"></div>';
echo '<div class="moon__crater moon__crater3"></div>';
echo '';
echo '<div class="star star1"></div>';
echo '<div class="star star2"></div>';
echo '<div class="star star3"></div>';
echo '<div class="star star4"></div>';
echo '<div class="star star5"></div>';
echo '';
echo '<div class="error">';
echo '<div class="error__title">404</div>';
echo '<div class="error__subtitle">Hmmm...</div>';
echo '<div class="error__description">It looks like one of the  developers fell asleep</div>';
echo '<button class="error__button error__button--active">LOGIN</button>';
echo '<button class="error__button">CONTACT</button>';
echo '</div>';
echo '';
echo '<div class="astronaut">';
echo '<div class="astronaut__backpack"></div>';
echo '<div class="astronaut__body"></div>';
echo '<div class="astronaut__body__chest"></div>';
echo '<div class="astronaut__arm-left1"></div>';
echo '<div class="astronaut__arm-left2"></div>';
echo '<div class="astronaut__arm-right1"></div>';
echo '<div class="astronaut__arm-right2"></div>';
echo '<div class="astronaut__arm-thumb-left"></div>';
echo '<div class="astronaut__arm-thumb-right"></div>';
echo '<div class="astronaut__leg-left"></div>';
echo '<div class="astronaut__leg-right"></div>';
echo '<div class="astronaut__foot-left"></div>';
echo '<div class="astronaut__foot-right"></div>';
echo '<div class="astronaut__wrist-left"></div>';
echo '<div class="astronaut__wrist-right"></div>';
echo '';
echo '<div class="astronaut__cord">';
echo '<canvas id="cord" height="500px" width="500px"></canvas>';
echo '</div>';
echo '';
echo '<div class="astronaut__head">';
echo '<canvas id="visor" width="60px" height="60px"></canvas>';
echo '<div class="astronaut__head-visor-flare1"></div>';
echo '<div class="astronaut__head-visor-flare2"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<style>';
echo '@font-face { font-family: Zekton; src: url('assets/webfonts/zekton-rg.tff'); }';
echo 'html,';
echo 'body {';
echo 'height: 100%;';
echo 'width: 100%;';
echo 'margin: 0px;';
echo 'background: linear-gradient(90deg, #2f3640 23%, #181b20 100%);';
echo '}';
echo '';
echo '.moon {';
echo 'background: linear-gradient(90deg, #d0d0d0 48%, #919191 100%);';
echo 'position: absolute;';
echo 'top: -100px;';
echo 'left: -300px;';
echo 'width: 900px;';
echo 'height: 900px;';
echo 'content: '';';
echo 'border-radius: 100%;';
echo 'box-shadow: 0px 0px 30px -4px rgba(0, 0, 0, 0.5);';
echo '}';
echo '';
echo '.moon__crater {';
echo 'position: absolute;';
echo 'content: '';';
echo 'border-radius: 100%;';
echo 'background: linear-gradient(90deg, #7a7a7a 38%, #c3c3c3 100%);';
echo 'opacity: 0.6;';
echo '}';
echo '';
echo '.moon__crater1 {';
echo 'top: 250px;';
echo 'left: 500px;';
echo 'width: 60px;';
echo 'height: 180px;';
echo '}';
echo '';
echo '.moon__crater2 {';
echo 'top: 650px;';
echo 'left: 340px;';
echo 'width: 40px;';
echo 'height: 80px;';
echo 'transform: rotate(55deg);';
echo '}';
echo '';
echo '.moon__crater3 {';
echo 'top: -20px;';
echo 'left: 40px;';
echo 'width: 65px;';
echo 'height: 120px;';
echo 'transform: rotate(250deg);';
echo '}';
echo '';
echo '.star {';
echo 'background: grey;';
echo 'position: absolute;';
echo 'width: 5px;';
echo 'height: 5px;';
echo 'content: '';';
echo 'border-radius: 100%;';
echo 'transform: rotate(250deg);';
echo 'opacity: 0.4;';
echo 'animation-name: shimmer;';
echo 'animation-duration: 1.5s;';
echo 'animation-iteration-count: infinite;';
echo 'animation-direction: alternate;';
echo '}';
echo '';
echo '@keyframes shimmer {';
echo 'from {';
echo 'opacity: 0;';
echo '}';
echo 'to {';
echo 'opacity: 0.7;';
echo '}';
echo '}';
echo '';
echo '.star1 {';
echo 'top: 40%;';
echo 'left: 50%;';
echo 'animation-delay: 1s;';
echo '}';
echo '';
echo '.star2 {';
echo 'top: 60%;';
echo 'left: 90%;';
echo 'animation-delay: 3s;';
echo '}';
echo '';
echo '.star3 {';
echo 'top: 10%;';
echo 'left: 70%;';
echo 'animation-delay: 2s;';
echo '}';
echo '';
echo '.star4 {';
echo 'top: 90%;';
echo 'left: 40%;';
echo '}';
echo '';
echo '.star5 {';
echo 'top: 20%;';
echo 'left: 30%;';
echo 'animation-delay: 0.5s;';
echo '}';
echo '';
echo '.error {';
echo 'position: absolute;';
echo 'left: 100px;';
echo 'top: 400px;';
echo 'transform: translateY(-60%);';
echo 'font-family: 'Zekton', cursive;';
echo 'color: #363e49;';
echo '}';
echo '';
echo '.error__title {';
echo 'font-size: 10em;';
echo '}';
echo '';
echo '.error__subtitle {';
echo 'font-size: 2em;';
echo '}';
echo '';
echo '.error__description {';
echo 'opacity: 0.5;';
echo '}';
echo '';
echo '.error__button {';
echo 'min-width: 7em;';
echo 'margin-top: 3em;';
echo 'margin-right: 0.5em;';
echo 'padding: 0.5em 2em;';
echo 'outline: none;';
echo 'border: 2px solid #2f3640;';
echo 'background-color: transparent;';
echo 'border-radius: 8em;';
echo 'color: #576375;';
echo 'cursor: pointer;';
echo 'transition-duration: 0.2s;';
echo 'font-size: 0.75em;';
echo 'font-family: 'Zekton', cursive;';
echo '}';
echo '';
echo '.error__button:hover {';
echo 'color: #21252c;';
echo '}';
echo '';
echo '.error__button--active {';
echo 'background-color: #e67e22;';
echo 'border: 2px solid #e67e22;';
echo 'color: white;';
echo '}';
echo '';
echo '.error__button--active:hover {';
echo 'box-shadow: 0px 0px 8px 0px rgba(0, 0, 0, 0.5);';
echo 'color: white;';
echo '}';
echo '';
echo '.astronaut {';
echo 'position: absolute;';
echo 'width: 185px;';
echo 'height: 300px;';
echo 'left: 70%;';
echo 'top: 50%;';
echo 'transform: translate(-50%, -50%) rotate(20deg) scale(1.2);';
echo '}';
echo '';
echo '.astronaut__head {';
echo 'background-color: white;';
echo 'position: absolute;';
echo 'top: 60px;';
echo 'left: 60px;';
echo 'width: 60px;';
echo 'height: 60px;';
echo 'content: '';';
echo 'border-radius: 2em;';
echo '}';
echo '';
echo '.astronaut__head-visor-flare1 {';
echo 'background-color: #7f8fa6;';
echo 'position: absolute;';
echo 'top: 28px;';
echo 'left: 40px;';
echo 'width: 10px;';
echo 'height: 10px;';
echo 'content: '';';
echo 'border-radius: 2em;';
echo 'opacity: 0.5;';
echo '}';
echo '';
echo '.astronaut__head-visor-flare2 {';
echo 'background-color: #718093;';
echo 'position: absolute;';
echo 'top: 40px;';
echo 'left: 38px;';
echo 'width: 5px;';
echo 'height: 5px;';
echo 'content: '';';
echo 'border-radius: 2em;';
echo 'opacity: 0.3;';
echo '}';
echo '';
echo '.astronaut__backpack {';
echo 'background-color: #bfbfbf;';
echo 'position: absolute;';
echo 'top: 90px;';
echo 'left: 47px;';
echo 'width: 86px;';
echo 'height: 90px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo '}';
echo '';
echo '.astronaut__body {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 115px;';
echo 'left: 55px;';
echo 'width: 70px;';
echo 'height: 80px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo '}';
echo '';
echo '.astronaut__body__chest {';
echo 'background-color: #d9d9d9;';
echo 'position: absolute;';
echo 'top: 140px;';
echo 'left: 68px;';
echo 'width: 45px;';
echo 'height: 25px;';
echo 'content: '';';
echo 'border-radius: 6px;';
echo '}';
echo '';
echo '.astronaut__arm-left1 {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 127px;';
echo 'left: 9px;';
echo 'width: 65px;';
echo 'height: 20px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo 'transform: rotate(-30deg);';
echo '}';
echo '';
echo '.astronaut__arm-left2 {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 102px;';
echo 'left: 7px;';
echo 'width: 20px;';
echo 'height: 45px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo 'transform: rotate(-12deg);';
echo 'border-top-left-radius: 8em;';
echo 'border-top-right-radius: 8em;';
echo '}';
echo '';
echo '.astronaut__arm-right1 {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 113px;';
echo 'left: 100px;';
echo 'width: 65px;';
echo 'height: 20px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo 'transform: rotate(-10deg);';
echo '}';
echo '';
echo '.astronaut__arm-right2 {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 78px;';
echo 'left: 141px;';
echo 'width: 20px;';
echo 'height: 45px;';
echo 'content: '';';
echo 'border-radius: 8px;';
echo 'transform: rotate(-10deg);';
echo 'border-top-left-radius: 8em;';
echo 'border-top-right-radius: 8em;';
echo '}';
echo '';
echo '.astronaut__arm-thumb-left {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 110px;';
echo 'left: 21px;';
echo 'width: 10px;';
echo 'height: 6px;';
echo 'content: '';';
echo 'border-radius: 8em;';
echo 'transform: rotate(-35deg);';
echo '}';
echo '';
echo '.astronaut__arm-thumb-right {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 90px;';
echo 'left: 133px;';
echo 'width: 10px;';
echo 'height: 6px;';
echo 'content: '';';
echo 'border-radius: 8em;';
echo 'transform: rotate(20deg);';
echo '}';
echo '';
echo '.astronaut__wrist-left {';
echo 'background-color: #e67e22;';
echo 'position: absolute;';
echo 'top: 122px;';
echo 'left: 6.5px;';
echo 'width: 21px;';
echo 'height: 4px;';
echo 'content: '';';
echo 'border-radius: 8em;';
echo 'transform: rotate(-15deg);';
echo '}';
echo '';
echo '.astronaut__wrist-right {';
echo 'background-color: #e67e22;';
echo 'position: absolute;';
echo 'top: 98px;';
echo 'left: 141px;';
echo 'width: 21px;';
echo 'height: 4px;';
echo 'content: '';';
echo 'border-radius: 8em;';
echo 'transform: rotate(-10deg);';
echo '}';
echo '';
echo '.astronaut__leg-left {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 188px;';
echo 'left: 50px;';
echo 'width: 23px;';
echo 'height: 75px;';
echo 'content: '';';
echo 'transform: rotate(10deg);';
echo '}';
echo '';
echo '.astronaut__leg-right {';
echo 'background-color: #e6e6e6;';
echo 'position: absolute;';
echo 'top: 188px;';
echo 'left: 108px;';
echo 'width: 23px;';
echo 'height: 75px;';
echo 'content: '';';
echo 'transform: rotate(-10deg);';
echo '}';
echo '';
echo '.astronaut__foot-left {';
echo 'background-color: white;';
echo 'position: absolute;';
echo 'top: 240px;';
echo 'left: 43px;';
echo 'width: 28px;';
echo 'height: 20px;';
echo 'content: '';';
echo 'transform: rotate(10deg);';
echo 'border-radius: 3px;';
echo 'border-top-left-radius: 8em;';
echo 'border-top-right-radius: 8em;';
echo 'border-bottom: 4px solid #e67e22;';
echo '}';
echo '';
echo '.astronaut__foot-right {';
echo 'background-color: white;';
echo 'position: absolute;';
echo 'top: 240px;';
echo 'left: 111px;';
echo 'width: 28px;';
echo 'height: 20px;';
echo 'content: '';';
echo 'transform: rotate(-10deg);';
echo 'border-radius: 3px;';
echo 'border-top-left-radius: 8em;';
echo 'border-top-right-radius: 8em;';
echo 'border-bottom: 4px solid #e67e22;';
echo '}';
echo '';
echo '</style>';
echo '';
echo '<script>';
echo 'function drawVisor() {';
echo 'const canvas = document.getElementById('visor');';
echo 'const ctx = canvas.getContext('2d');';
echo '';
echo 'ctx.beginPath();';
echo 'ctx.moveTo(5, 45);';
echo 'ctx.bezierCurveTo(15, 64, 45, 64, 55, 45);';
echo '';
echo 'ctx.lineTo(55, 20);';
echo 'ctx.bezierCurveTo(55, 15, 50, 10, 45, 10);';
echo '';
echo 'ctx.lineTo(15, 10);';
echo '';
echo 'ctx.bezierCurveTo(15, 10, 5, 10, 5, 20);';
echo 'ctx.lineTo(5, 45);';
echo '';
echo 'ctx.fillStyle = '#2f3640';';
echo 'ctx.strokeStyle = '#f5f6fa';';
echo 'ctx.fill();';
echo 'ctx.stroke();';
echo '}';
echo '';
echo 'const cordCanvas = document.getElementById('cord');';
echo 'const ctx = cordCanvas.getContext('2d');';
echo '';
echo 'let y1 = 160;';
echo 'let y2 = 100;';
echo 'let y3 = 100;';
echo '';
echo 'let y1Forward = true;';
echo 'let y2Forward = false;';
echo 'let y3Forward = true;';
echo '';
echo 'function animate() {';
echo 'requestAnimationFrame(animate);';
echo 'ctx.clearRect(0, 0, innerWidth, innerHeight);';
echo '';
echo 'ctx.beginPath();';
echo 'ctx.moveTo(130, 170);';
echo 'ctx.bezierCurveTo(250, y1, 345, y2, 400, y3);';
echo '';
echo 'ctx.strokeStyle = 'white';';
echo 'ctx.lineWidth = 8;';
echo 'ctx.stroke();';
echo '';
echo '';
echo 'if (y1 === 100) {';
echo 'y1Forward = true;';
echo '}';
echo '';
echo 'if (y1 === 300) {';
echo 'y1Forward = false;';
echo '}';
echo '';
echo 'if (y2 === 100) {';
echo 'y2Forward = true;';
echo '}';
echo '';
echo 'if (y2 === 310) {';
echo 'y2Forward = false;';
echo '}';
echo '';
echo 'if (y3 === 100) {';
echo 'y3Forward = true;';
echo '}';
echo '';
echo 'if (y3 === 317) {';
echo 'y3Forward = false;';
echo '}';
echo '';
echo 'y1Forward ? y1 += 1 : y1 -= 1;';
echo 'y2Forward ? y2 += 1 : y2 -= 1;';
echo 'y3Forward ? y3 += 1 : y3 -= 1;';
echo '}';
echo '';
echo 'drawVisor();';
echo 'animate();';
echo '</script>';
echo '</html>';
?>